apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-web-app
  namespace: java-web-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: java-web-app.lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: java-web-app
                port:
                  number: 80
