apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: java-web-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./java-web-app/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: cicd-testing
  targetNamespace: java-web-app
