apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ste-test-cicd
  namespace: flux
spec:
  interval: 1m
  path: ./clusters/ste-test-cicd
  prune: true
  sourceRef:
    kind: GitRepository
    name: cicd-testing
