apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - imgrepo.yaml
  - imgpolicy.yaml
  - img-automation.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: harbor.lab.local/cicd123/cicd123
    newTag: 1.0.0

